// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/http"

	"github.com/e-hua/netbula/internal/app/manager"
	"github.com/e-hua/netbula/internal/app/worker"
	"github.com/e-hua/netbula/internal/node"
	"github.com/e-hua/netbula/internal/task"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockManagerService creates a new instance of MockManagerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManagerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManagerService {
	mock := &MockManagerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManagerService is an autogenerated mock type for the ManagerService type
type MockManagerService struct {
	mock.Mock
}

type MockManagerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManagerService) EXPECT() *MockManagerService_Expecter {
	return &MockManagerService_Expecter{mock: &_m.Mock}
}

// AddTaskEvent provides a mock function for the type MockManagerService
func (_mock *MockManagerService) AddTaskEvent(te task.TaskEvent) {
	_mock.Called(te)
	return
}

// MockManagerService_AddTaskEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTaskEvent'
type MockManagerService_AddTaskEvent_Call struct {
	*mock.Call
}

// AddTaskEvent is a helper method to define mock.On call
//   - te task.TaskEvent
func (_e *MockManagerService_Expecter) AddTaskEvent(te interface{}) *MockManagerService_AddTaskEvent_Call {
	return &MockManagerService_AddTaskEvent_Call{Call: _e.mock.On("AddTaskEvent", te)}
}

func (_c *MockManagerService_AddTaskEvent_Call) Run(run func(te task.TaskEvent)) *MockManagerService_AddTaskEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 task.TaskEvent
		if args[0] != nil {
			arg0 = args[0].(task.TaskEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManagerService_AddTaskEvent_Call) Return() *MockManagerService_AddTaskEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManagerService_AddTaskEvent_Call) RunAndReturn(run func(te task.TaskEvent)) *MockManagerService_AddTaskEvent_Call {
	_c.Run(run)
	return _c
}

// AddWorkerAndClient provides a mock function for the type MockManagerService
func (_mock *MockManagerService) AddWorkerAndClient(workerInfo *worker.Worker, client *http.Client) {
	_mock.Called(workerInfo, client)
	return
}

// MockManagerService_AddWorkerAndClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWorkerAndClient'
type MockManagerService_AddWorkerAndClient_Call struct {
	*mock.Call
}

// AddWorkerAndClient is a helper method to define mock.On call
//   - workerInfo *worker.Worker
//   - client *http.Client
func (_e *MockManagerService_Expecter) AddWorkerAndClient(workerInfo interface{}, client interface{}) *MockManagerService_AddWorkerAndClient_Call {
	return &MockManagerService_AddWorkerAndClient_Call{Call: _e.mock.On("AddWorkerAndClient", workerInfo, client)}
}

func (_c *MockManagerService_AddWorkerAndClient_Call) Run(run func(workerInfo *worker.Worker, client *http.Client)) *MockManagerService_AddWorkerAndClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *worker.Worker
		if args[0] != nil {
			arg0 = args[0].(*worker.Worker)
		}
		var arg1 *http.Client
		if args[1] != nil {
			arg1 = args[1].(*http.Client)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManagerService_AddWorkerAndClient_Call) Return() *MockManagerService_AddWorkerAndClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManagerService_AddWorkerAndClient_Call) RunAndReturn(run func(workerInfo *worker.Worker, client *http.Client)) *MockManagerService_AddWorkerAndClient_Call {
	_c.Run(run)
	return _c
}

// GetNodes provides a mock function for the type MockManagerService
func (_mock *MockManagerService) GetNodes() []node.Node {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNodes")
	}

	var r0 []node.Node
	if returnFunc, ok := ret.Get(0).(func() []node.Node); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]node.Node)
		}
	}
	return r0
}

// MockManagerService_GetNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodes'
type MockManagerService_GetNodes_Call struct {
	*mock.Call
}

// GetNodes is a helper method to define mock.On call
func (_e *MockManagerService_Expecter) GetNodes() *MockManagerService_GetNodes_Call {
	return &MockManagerService_GetNodes_Call{Call: _e.mock.On("GetNodes")}
}

func (_c *MockManagerService_GetNodes_Call) Run(run func()) *MockManagerService_GetNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManagerService_GetNodes_Call) Return(nodes []node.Node) *MockManagerService_GetNodes_Call {
	_c.Call.Return(nodes)
	return _c
}

func (_c *MockManagerService_GetNodes_Call) RunAndReturn(run func() []node.Node) *MockManagerService_GetNodes_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function for the type MockManagerService
func (_mock *MockManagerService) GetTask(taskId uuid.UUID) (*task.Task, error) {
	ret := _mock.Called(taskId)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *task.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*task.Task, error)); ok {
		return returnFunc(taskId)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *task.Task); ok {
		r0 = returnFunc(taskId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(taskId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerService_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockManagerService_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - taskId uuid.UUID
func (_e *MockManagerService_Expecter) GetTask(taskId interface{}) *MockManagerService_GetTask_Call {
	return &MockManagerService_GetTask_Call{Call: _e.mock.On("GetTask", taskId)}
}

func (_c *MockManagerService_GetTask_Call) Run(run func(taskId uuid.UUID)) *MockManagerService_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManagerService_GetTask_Call) Return(task1 *task.Task, err error) *MockManagerService_GetTask_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockManagerService_GetTask_Call) RunAndReturn(run func(taskId uuid.UUID) (*task.Task, error)) *MockManagerService_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasks provides a mock function for the type MockManagerService
func (_mock *MockManagerService) GetTasks() ([]*task.Task, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 []*task.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*task.Task, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*task.Task); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerService_GetTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasks'
type MockManagerService_GetTasks_Call struct {
	*mock.Call
}

// GetTasks is a helper method to define mock.On call
func (_e *MockManagerService_Expecter) GetTasks() *MockManagerService_GetTasks_Call {
	return &MockManagerService_GetTasks_Call{Call: _e.mock.On("GetTasks")}
}

func (_c *MockManagerService_GetTasks_Call) Run(run func()) *MockManagerService_GetTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManagerService_GetTasks_Call) Return(task1 []*task.Task, err error) *MockManagerService_GetTasks_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockManagerService_GetTasks_Call) RunAndReturn(run func() ([]*task.Task, error)) *MockManagerService_GetTasks_Call {
	_c.Call.Return(run)
	return _c
}

// SelectWorker provides a mock function for the type MockManagerService
func (_mock *MockManagerService) SelectWorker(t task.Task) (uuid.UUID, error) {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for SelectWorker")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(task.Task) (uuid.UUID, error)); ok {
		return returnFunc(t)
	}
	if returnFunc, ok := ret.Get(0).(func(task.Task) uuid.UUID); ok {
		r0 = returnFunc(t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(task.Task) error); ok {
		r1 = returnFunc(t)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerService_SelectWorker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectWorker'
type MockManagerService_SelectWorker_Call struct {
	*mock.Call
}

// SelectWorker is a helper method to define mock.On call
//   - t task.Task
func (_e *MockManagerService_Expecter) SelectWorker(t interface{}) *MockManagerService_SelectWorker_Call {
	return &MockManagerService_SelectWorker_Call{Call: _e.mock.On("SelectWorker", t)}
}

func (_c *MockManagerService_SelectWorker_Call) Run(run func(t task.Task)) *MockManagerService_SelectWorker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 task.Task
		if args[0] != nil {
			arg0 = args[0].(task.Task)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManagerService_SelectWorker_Call) Return(uUID uuid.UUID, err error) *MockManagerService_SelectWorker_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockManagerService_SelectWorker_Call) RunAndReturn(run func(t task.Task) (uuid.UUID, error)) *MockManagerService_SelectWorker_Call {
	_c.Call.Return(run)
	return _c
}

// SendTasksForever provides a mock function for the type MockManagerService
func (_mock *MockManagerService) SendTasksForever(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockManagerService_SendTasksForever_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTasksForever'
type MockManagerService_SendTasksForever_Call struct {
	*mock.Call
}

// SendTasksForever is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManagerService_Expecter) SendTasksForever(ctx interface{}) *MockManagerService_SendTasksForever_Call {
	return &MockManagerService_SendTasksForever_Call{Call: _e.mock.On("SendTasksForever", ctx)}
}

func (_c *MockManagerService_SendTasksForever_Call) Run(run func(ctx context.Context)) *MockManagerService_SendTasksForever_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManagerService_SendTasksForever_Call) Return() *MockManagerService_SendTasksForever_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManagerService_SendTasksForever_Call) RunAndReturn(run func(ctx context.Context)) *MockManagerService_SendTasksForever_Call {
	_c.Run(run)
	return _c
}

// SendWork provides a mock function for the type MockManagerService
func (_mock *MockManagerService) SendWork() (*task.TaskEvent, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendWork")
	}

	var r0 *task.TaskEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*task.TaskEvent, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *task.TaskEvent); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.TaskEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerService_SendWork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendWork'
type MockManagerService_SendWork_Call struct {
	*mock.Call
}

// SendWork is a helper method to define mock.On call
func (_e *MockManagerService_Expecter) SendWork() *MockManagerService_SendWork_Call {
	return &MockManagerService_SendWork_Call{Call: _e.mock.On("SendWork")}
}

func (_c *MockManagerService_SendWork_Call) Run(run func()) *MockManagerService_SendWork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManagerService_SendWork_Call) Return(targetEvent *task.TaskEvent, retErr error) *MockManagerService_SendWork_Call {
	_c.Call.Return(targetEvent, retErr)
	return _c
}

func (_c *MockManagerService_SendWork_Call) RunAndReturn(run func() (*task.TaskEvent, error)) *MockManagerService_SendWork_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTasksForever provides a mock function for the type MockManagerService
func (_mock *MockManagerService) UpdateTasksForever(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockManagerService_UpdateTasksForever_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTasksForever'
type MockManagerService_UpdateTasksForever_Call struct {
	*mock.Call
}

// UpdateTasksForever is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManagerService_Expecter) UpdateTasksForever(ctx interface{}) *MockManagerService_UpdateTasksForever_Call {
	return &MockManagerService_UpdateTasksForever_Call{Call: _e.mock.On("UpdateTasksForever", ctx)}
}

func (_c *MockManagerService_UpdateTasksForever_Call) Run(run func(ctx context.Context)) *MockManagerService_UpdateTasksForever_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManagerService_UpdateTasksForever_Call) Return() *MockManagerService_UpdateTasksForever_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManagerService_UpdateTasksForever_Call) RunAndReturn(run func(ctx context.Context)) *MockManagerService_UpdateTasksForever_Call {
	_c.Run(run)
	return _c
}

// UpdateWorkerNodes provides a mock function for the type MockManagerService
func (_mock *MockManagerService) UpdateWorkerNodes() {
	_mock.Called()
	return
}

// MockManagerService_UpdateWorkerNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkerNodes'
type MockManagerService_UpdateWorkerNodes_Call struct {
	*mock.Call
}

// UpdateWorkerNodes is a helper method to define mock.On call
func (_e *MockManagerService_Expecter) UpdateWorkerNodes() *MockManagerService_UpdateWorkerNodes_Call {
	return &MockManagerService_UpdateWorkerNodes_Call{Call: _e.mock.On("UpdateWorkerNodes")}
}

func (_c *MockManagerService_UpdateWorkerNodes_Call) Run(run func()) *MockManagerService_UpdateWorkerNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManagerService_UpdateWorkerNodes_Call) Return() *MockManagerService_UpdateWorkerNodes_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManagerService_UpdateWorkerNodes_Call) RunAndReturn(run func()) *MockManagerService_UpdateWorkerNodes_Call {
	_c.Run(run)
	return _c
}

// NewMockCluster creates a new instance of MockCluster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCluster(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCluster {
	mock := &MockCluster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCluster is an autogenerated mock type for the Cluster type
type MockCluster struct {
	mock.Mock
}

type MockCluster_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCluster) EXPECT() *MockCluster_Expecter {
	return &MockCluster_Expecter{mock: &_m.Mock}
}

// AddClient provides a mock function for the type MockCluster
func (_mock *MockCluster) AddClient(workerId uuid.UUID, client *http.Client) {
	_mock.Called(workerId, client)
	return
}

// MockCluster_AddClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddClient'
type MockCluster_AddClient_Call struct {
	*mock.Call
}

// AddClient is a helper method to define mock.On call
//   - workerId uuid.UUID
//   - client *http.Client
func (_e *MockCluster_Expecter) AddClient(workerId interface{}, client interface{}) *MockCluster_AddClient_Call {
	return &MockCluster_AddClient_Call{Call: _e.mock.On("AddClient", workerId, client)}
}

func (_c *MockCluster_AddClient_Call) Run(run func(workerId uuid.UUID, client *http.Client)) *MockCluster_AddClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 *http.Client
		if args[1] != nil {
			arg1 = args[1].(*http.Client)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCluster_AddClient_Call) Return() *MockCluster_AddClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCluster_AddClient_Call) RunAndReturn(run func(workerId uuid.UUID, client *http.Client)) *MockCluster_AddClient_Call {
	_c.Run(run)
	return _c
}

// GetClient provides a mock function for the type MockCluster
func (_mock *MockCluster) GetClient(workerId uuid.UUID) (*http.Client, error) {
	ret := _mock.Called(workerId)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 *http.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*http.Client, error)); ok {
		return returnFunc(workerId)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *http.Client); ok {
		r0 = returnFunc(workerId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(workerId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCluster_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type MockCluster_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
//   - workerId uuid.UUID
func (_e *MockCluster_Expecter) GetClient(workerId interface{}) *MockCluster_GetClient_Call {
	return &MockCluster_GetClient_Call{Call: _e.mock.On("GetClient", workerId)}
}

func (_c *MockCluster_GetClient_Call) Run(run func(workerId uuid.UUID)) *MockCluster_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCluster_GetClient_Call) Return(client *http.Client, err error) *MockCluster_GetClient_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockCluster_GetClient_Call) RunAndReturn(run func(workerId uuid.UUID) (*http.Client, error)) *MockCluster_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodes provides a mock function for the type MockCluster
func (_mock *MockCluster) GetNodes() []node.Node {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNodes")
	}

	var r0 []node.Node
	if returnFunc, ok := ret.Get(0).(func() []node.Node); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]node.Node)
		}
	}
	return r0
}

// MockCluster_GetNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodes'
type MockCluster_GetNodes_Call struct {
	*mock.Call
}

// GetNodes is a helper method to define mock.On call
func (_e *MockCluster_Expecter) GetNodes() *MockCluster_GetNodes_Call {
	return &MockCluster_GetNodes_Call{Call: _e.mock.On("GetNodes")}
}

func (_c *MockCluster_GetNodes_Call) Run(run func()) *MockCluster_GetNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCluster_GetNodes_Call) Return(nodes []node.Node) *MockCluster_GetNodes_Call {
	_c.Call.Return(nodes)
	return _c
}

func (_c *MockCluster_GetNodes_Call) RunAndReturn(run func() []node.Node) *MockCluster_GetNodes_Call {
	_c.Call.Return(run)
	return _c
}

// SendTask provides a mock function for the type MockCluster
func (_mock *MockCluster) SendTask(targetWorkerId uuid.UUID, taskEvent task.TaskEvent) (*task.Task, error) {
	ret := _mock.Called(targetWorkerId, taskEvent)

	if len(ret) == 0 {
		panic("no return value specified for SendTask")
	}

	var r0 *task.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, task.TaskEvent) (*task.Task, error)); ok {
		return returnFunc(targetWorkerId, taskEvent)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, task.TaskEvent) *task.Task); ok {
		r0 = returnFunc(targetWorkerId, taskEvent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, task.TaskEvent) error); ok {
		r1 = returnFunc(targetWorkerId, taskEvent)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCluster_SendTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTask'
type MockCluster_SendTask_Call struct {
	*mock.Call
}

// SendTask is a helper method to define mock.On call
//   - targetWorkerId uuid.UUID
//   - taskEvent task.TaskEvent
func (_e *MockCluster_Expecter) SendTask(targetWorkerId interface{}, taskEvent interface{}) *MockCluster_SendTask_Call {
	return &MockCluster_SendTask_Call{Call: _e.mock.On("SendTask", targetWorkerId, taskEvent)}
}

func (_c *MockCluster_SendTask_Call) Run(run func(targetWorkerId uuid.UUID, taskEvent task.TaskEvent)) *MockCluster_SendTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 task.TaskEvent
		if args[1] != nil {
			arg1 = args[1].(task.TaskEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCluster_SendTask_Call) Return(task1 *task.Task, err error) *MockCluster_SendTask_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockCluster_SendTask_Call) RunAndReturn(run func(targetWorkerId uuid.UUID, taskEvent task.TaskEvent) (*task.Task, error)) *MockCluster_SendTask_Call {
	_c.Call.Return(run)
	return _c
}

// StopTask provides a mock function for the type MockCluster
func (_mock *MockCluster) StopTask(targetWorkerId uuid.UUID, taskIdToStop uuid.UUID) error {
	ret := _mock.Called(targetWorkerId, taskIdToStop)

	if len(ret) == 0 {
		panic("no return value specified for StopTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(targetWorkerId, taskIdToStop)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCluster_StopTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopTask'
type MockCluster_StopTask_Call struct {
	*mock.Call
}

// StopTask is a helper method to define mock.On call
//   - targetWorkerId uuid.UUID
//   - taskIdToStop uuid.UUID
func (_e *MockCluster_Expecter) StopTask(targetWorkerId interface{}, taskIdToStop interface{}) *MockCluster_StopTask_Call {
	return &MockCluster_StopTask_Call{Call: _e.mock.On("StopTask", targetWorkerId, taskIdToStop)}
}

func (_c *MockCluster_StopTask_Call) Run(run func(targetWorkerId uuid.UUID, taskIdToStop uuid.UUID)) *MockCluster_StopTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCluster_StopTask_Call) Return(err error) *MockCluster_StopTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCluster_StopTask_Call) RunAndReturn(run func(targetWorkerId uuid.UUID, taskIdToStop uuid.UUID) error) *MockCluster_StopTask_Call {
	_c.Call.Return(run)
	return _c
}

// SyncTasks provides a mock function for the type MockCluster
func (_mock *MockCluster) SyncTasks(state manager.State) {
	_mock.Called(state)
	return
}

// MockCluster_SyncTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncTasks'
type MockCluster_SyncTasks_Call struct {
	*mock.Call
}

// SyncTasks is a helper method to define mock.On call
//   - state manager.State
func (_e *MockCluster_Expecter) SyncTasks(state interface{}) *MockCluster_SyncTasks_Call {
	return &MockCluster_SyncTasks_Call{Call: _e.mock.On("SyncTasks", state)}
}

func (_c *MockCluster_SyncTasks_Call) Run(run func(state manager.State)) *MockCluster_SyncTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 manager.State
		if args[0] != nil {
			arg0 = args[0].(manager.State)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCluster_SyncTasks_Call) Return() *MockCluster_SyncTasks_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCluster_SyncTasks_Call) RunAndReturn(run func(state manager.State)) *MockCluster_SyncTasks_Call {
	_c.Run(run)
	return _c
}

// UpdateWorkerNodes provides a mock function for the type MockCluster
func (_mock *MockCluster) UpdateWorkerNodes(state manager.State) {
	_mock.Called(state)
	return
}

// MockCluster_UpdateWorkerNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkerNodes'
type MockCluster_UpdateWorkerNodes_Call struct {
	*mock.Call
}

// UpdateWorkerNodes is a helper method to define mock.On call
//   - state manager.State
func (_e *MockCluster_Expecter) UpdateWorkerNodes(state interface{}) *MockCluster_UpdateWorkerNodes_Call {
	return &MockCluster_UpdateWorkerNodes_Call{Call: _e.mock.On("UpdateWorkerNodes", state)}
}

func (_c *MockCluster_UpdateWorkerNodes_Call) Run(run func(state manager.State)) *MockCluster_UpdateWorkerNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 manager.State
		if args[0] != nil {
			arg0 = args[0].(manager.State)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCluster_UpdateWorkerNodes_Call) Return() *MockCluster_UpdateWorkerNodes_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCluster_UpdateWorkerNodes_Call) RunAndReturn(run func(state manager.State)) *MockCluster_UpdateWorkerNodes_Call {
	_c.Run(run)
	return _c
}
