/*
Copyright © 2026 NAME HERE <EMAIL ADDRESS>
*/
package cmd

import (
	"fmt"

	ctlCommand "github.com/e-hua/netbula/cmd/control"
	"github.com/e-hua/netbula/internal/app/control"
	"github.com/spf13/cobra"
)

// controlCmd represents the control command
var controlCmd = &cobra.Command{
	Use:   "control",
	Short: "Control command to interact with the Netbula cluster",
	Long: `Netbula control command
	The control instance acts as a client to the manager's API. 
	It allows users to:
	- Schedule new tasks (netbula control run)
	- View the status of tasks and nodes (netbula control tasks/nodes)
	- Stop running tasks (netbula control stop)

	It uses a secure HTTPS connection 
	and requires an admin token for authentication 
	plus the fingerprint of manager's TLS certificate to verify the manager public key.
	`,
	Run: func(cmd *cobra.Command, args []string) {
		managerAddress, _ := cmd.Flags().GetString("manager-address")
		token, _ := cmd.Flags().GetString("token")
		fingerprint, _ := cmd.Flags().GetString("fingerprint")

		// Update/Store the manager address and token
		config := control.Run(managerAddress, token, fingerprint)

		fmt.Printf(
			"Current target manager address: %s\n",
			config.ManagerServerAddress,
		)
		fmt.Printf(
			"Current connection token with manager server: %s\n",
			config.ControlToken,
		)
		fmt.Printf(
			"Current stored fingerprint of the manager server's TLS certificate: %s\n",
			config.ManagerCertFingerprint,
		)
	},
}

func init() {
	rootCmd.AddCommand(controlCmd)

	controlCmd.AddCommand(ctlCommand.RunCmd)
	controlCmd.AddCommand(ctlCommand.StopCmd)
	controlCmd.AddCommand(ctlCommand.TasksCmd)
	controlCmd.AddCommand(ctlCommand.NodesCmd)

	controlCmd.PersistentFlags().StringP(
		"manager-address",
		"m",
		"",
		"The HTTPS address of the manager API (Example: localhost:5555)",
	)

	controlCmd.PersistentFlags().StringP(
		"token",
		"t",
		"",
		"The admin token generated by the manager for authentication (Example: 0123456789abcde)",
	)

	controlCmd.PersistentFlags().StringP(
		"fingerprint",
		"f",
		"",
		"Hexadecimal encoded hash of the manager's TLS certificate (Example: 0123456789abcde)",
	)
}
